/*
 * This file is part of Orchestrion.
 *
 * Copyright (C) 2026 Matthieu Hodgkinson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#pragma once

// GENERATED by tools/extract_musescore_placeholders.py from
// MuseScore/share/locale/musescore_*.ts -- do not edit by hand.
//
// The texts MuseScore's new-score wizard leaves in the title and composer
// meta tags when the user fills in nothing, in every language MuseScore
// ships. A score carrying one of these has no real title or composer.

namespace dgk::musescore_placeholders
{
// clang-format off
// qsTrc("project", "Untitled score")
inline constexpr const char16_t *const titles[] = {
    u"Untitled score", // en
    u"Bevard\u0117 partit\u016bra", // lt — Bevardė partitūra
    u"B\u1ea3n nh\u1ea1c kh\u00f4ng t\u00ean", // vi — Bản nhạc không tên
    u"Naamlose partituur", // af
    u"Naamloze partituur", // nl
    u"Namnl\u00f6s not", // sv — Namnlös not
    u"Neimenovani notni zapis", // hr
    u"Nenaslovljeni notni zapis", // sl
    u"Nepojmenovan\u00fd notov\u00fd z\u00e1pis", // cs — Nepojmenovaný notový zápis
    u"Nimet\u00f6n partituuri", // fi — Nimetön partituuri
    u"N\u00e9vtelen kotta", // hu — Névtelen kotta
    u"Partition sans titre", // fr
    u"Partitur uten navn", // nb
    u"Partitura ensin t\u00edtulu", // ast — Partitura ensin títulu
    u"Partitura sem t\u00edtulo", // pt, pt_BR — Partitura sem título
    u"Partitura sense t\u00edtol", // ca, ca@valencia — Partitura sense títol
    u"Partitura senza titolo", // it
    u"Partitura sin t\u00edtulo", // es — Partitura sin título
    u"Partitur\u0103 f\u0103r\u0103 titlu", // ro — Partitură fără titlu
    u"Titel", // sv_SE
    u"Tytu\u0142", // pl — Tytuł
    u"Unavngivet nodeark", // da
    u"Unbenannte Partitur", // de
    u"\u00d3nevnt n\u00f3tabla\u00f0", // fo — Ónevnt nótablað
    u"\u0130simsiz partisyon", // tr — İsimsiz partisyon
    u"\u0411\u0435\u0437\u044b\u043c\u044f\u043d\u043d\u0430\u044f \u043f\u0430\u0440\u0442\u0438\u0442\u0443\u0440\u0430", // ru — Безымянная партитура
    u"\u041f\u0430\u0440\u0442\u0438\u0442\u0443\u0440\u0430 \u0431\u0435\u0437 \u043d\u0430\u0437\u0432\u0438", // uk — Партитура без назви
    u"\u05e4\u05e8\u05d8\u05d9\u05d8\u05d5\u05e8\u05d4 \u05dc\u05dc\u05d0 \u05db\u05d5\u05ea\u05e8\u05ea", // he — פרטיטורה ללא כותרת
    u"\u10e3\u10e1\u10d0\u10d7\u10d0\u10e3\u10e0\u10dd \u10de\u10d0\u10e0\u10e2\u10d8\u10e2\u10e3\u10e0\u10d0", // ka — უსათაურო პარტიტურა
    u"\u672a\u547d\u540d\u4e50\u8c31", // zh_CN — 未命名乐谱
    u"\u672a\u547d\u540d\u6a02\u8b5c", // zh_HK, zh_TW — 未命名樂譜
    u"\u7121\u984c\u306e\u30b9\u30b3\u30a2", // ja — 無題のスコア
    u"\uc774\ub984 \uc5c6\ub294 \uc545\ubcf4", // ko — 이름 없는 악보
};

// qsTrc("project", "Composer / arranger")
inline constexpr const char16_t *const composers[] = {
    u"Composer / arranger", // en
    u"Besteci / Aranj\u00f6r", // tr — Besteci / Aranjör
    u"Componist / arrangeur", // nl
    u"Compositeur / Arrangeur", // fr
    u"Compositor / arranjador", // ca, ca@valencia, pt, pt_BR
    u"Compositor / arranxista", // gl
    u"Compositor / arreglista", // es
    u"Compositor / iguador", // ast
    u"Compositore / arrangiatore", // it
    u"Compozitor / aranjor", // ro
    u"Komponis / verwerker", // af
    u"Komponist / Arrangeur", // de
    u"Komponist / arrang\u00f8r", // da, nb — Komponist / arrangør
    u"Komposit\u00f6r/arrang\u00f6r", // sv, sv_SE — Kompositör/arrangör
    u"Kompozitor / aran\u017eer", // hr — Kompozitor / aranžer
    u"Kompozitorius / aran\u017euotojas", // lt — Kompozitorius / aranžuotojas
    u"Kompozytor/aran\u017cer", // pl — Kompozytor/aranżer
    u"Kompo\u017citur/a / arran\u0121atur/a", // mt — Kompożitur/a / arranġatur/a
    u"Skladatel/aran\u017e\u00e9r", // cs — Skladatel/aranžér
    u"Skladatelj/priredba", // sl
    u"Skladate\u013e / aran\u017e\u00e9r", // sk — Skladateľ / aranžér
    u"S\u00e4velt\u00e4j\u00e4 / sovittaja", // fi — Säveltäjä / sovittaja
    u"T\u00f3naskald/\u00fatsetari", // fo — Tónaskald/útsetari
    u"Zeneszerz\u0151 / hangszerel\u0151", // hu — Zeneszerző / hangszerelő
    u"\u041a\u0430\u043c\u043f\u0430\u0437\u0456\u0442\u0430\u0440 / \u0430\u0440\u0430\u043d\u0436\u044b\u0440\u043e\u045e\u0448\u0447\u044b\u043a", // be — Кампазітар / аранжыроўшчык
    u"\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0442\u043e\u0440 / \u0430\u0440\u0430\u043d\u0436\u0438\u0440\u043e\u0432\u0449\u0438\u043a", // ru — Композитор / аранжировщик
    u"\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0442\u043e\u0440 / \u0430\u0440\u0430\u043d\u0436\u0443\u0432\u0430\u043b\u044c\u043d\u0438\u043a", // uk — Композитор / аранжувальник
    u"\u05d4\u05dc\u05d7\u05e0\u05d4 / \u05e2\u05d9\u05d1\u05d5\u05d3", // he — הלחנה / עיבוד
    u"\u10d9\u10dd\u10db\u10de\u10dd\u10d6\u10d8\u10e2\u10dd\u10e0\u10d8", // ka — კომპოზიტორი
    u"\u4f5c\u66f2 / \u7de8\u6392", // zh_HK — 作曲 / 編排
    u"\u4f5c\u66f2 / \u7de8\u66f2", // zh_TW — 作曲 / 編曲
    u"\u4f5c\u66f2 / \u7f16\u6392", // zh_CN — 作曲 / 编排
    u"\u4f5c\u66f2\u8005 / \u7de8\u66f2\u8005", // ja — 作曲者 / 編曲者
    u"\uc791\uace1\uac00 / \ud3b8\uace1\uac00", // ko — 작곡가 / 편곡가
};

// clang-format on
} // namespace dgk::musescore_placeholders
