#!/usr/bin/env python3
"""Regenerate src/OrchestrionShell/internal/MuseScorePlaceholderMetaTags.h.

MuseScore's new-score wizard fills the title and composer fields with
placeholder texts when the user leaves them blank ("Untitled score",
"Composer / arranger" — see GeneralInfoView.qml), localized in the UI language
of whoever created the score. Scores exported that way carry the placeholder
in their metadata, where it would otherwise be displayed as a genuine title or
composer. This script collects every translation MuseScore ships into a C++
table so that such tags can be recognized and ignored.

Run from the repository root after updating the MuseScore submodule:

    python3 tools/extract_musescore_placeholders.py
"""

import collections
import glob
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TS_GLOB = os.path.join(ROOT, "MuseScore", "share", "locale", "musescore_*.ts")
OUT = os.path.join(ROOT, "src", "OrchestrionShell", "internal",
                   "MuseScorePlaceholderMetaTags.h")

# (C++ array name, qsTrc("project", ...) source string)
PLACEHOLDERS = [
    ("titles", "Untitled score"),
    ("composers", "Composer / arranger"),
]


def collect():
    # source -> translation -> sorted language codes
    found = {src: collections.defaultdict(set) for _, src in PLACEHOLDERS}
    for path in sorted(glob.glob(TS_GLOB)):
        lang = os.path.basename(path)[len("musescore_"):-len(".ts")]
        for context in ET.parse(path).getroot().findall("context"):
            if context.findtext("name") != "project":
                continue
            for message in context.findall("message"):
                source = message.findtext("source")
                if source not in found:
                    continue
                translation = message.find("translation")
                text = (translation.text or "").strip() \
                    if translation is not None else ""
                if text:
                    found[source][text].add(lang)
    return found


def cxx_literal(text: str) -> str:
    # ASCII-only u"" literal, so the header is safe with any source charset.
    out = []
    for ch in text:
        if ch == '"' or ch == "\\":
            out.append("\\" + ch)
        elif 0x20 <= ord(ch) < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{ord(ch):04x}")
    return 'u"' + "".join(out) + '"'


def main() -> None:
    found = collect()
    lines = [
        "/*",
        " * This file is part of Orchestrion.",
        " *",
        " * Copyright (C) 2024 Matthieu Hodgkinson",
        " *",
        " * This program is free software: you can redistribute it and/or modify",
        " * it under the terms of the GNU General Public License as published by",
        " * the Free Software Foundation, either version 3 of the License, or",
        " * (at your option) any later version.",
        " *",
        " * This program is distributed in the hope that it will be useful,",
        " * but WITHOUT ANY WARRANTY; without even the implied warranty of",
        " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the",
        " * GNU General Public License for more details.",
        " *",
        " * You should have received a copy of the GNU General Public License",
        " * along with this program. If not, see <https://www.gnu.org/licenses/>.",
        " */",
        "#pragma once",
        "",
        "// GENERATED by tools/extract_musescore_placeholders.py from",
        "// MuseScore/share/locale/musescore_*.ts -- do not edit by hand.",
        "//",
        "// The texts MuseScore's new-score wizard leaves in the title and composer",
        "// meta tags when the user fills in nothing, in every language MuseScore",
        "// ships. A score carrying one of these has no real title or composer.",
        "",
        "namespace dgk::musescore_placeholders",
        "{",
        "// clang-format off",
    ]
    for name, source in PLACEHOLDERS:
        lines.append(f"// qsTrc(\"project\", \"{source}\")")
        lines.append(f"inline constexpr const char16_t *const {name}[] = {{")
        lines.append(f"    {cxx_literal(source)}, // en")
        for text, langs in sorted(found[source].items()):
            if text == source:
                continue
            literal = cxx_literal(text)
            # Spell out what an escaped literal says.
            readable = f" \u2014 {text}" if "\\u" in literal else ""
            lines.append(f"    {literal}, // {', '.join(sorted(langs))}{readable}")
        lines.append("};")
        lines.append("")
    lines.append("// clang-format on")
    lines.append("} // namespace dgk::musescore_placeholders")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    counts = ", ".join(f"{name}: {len(found[src]) + 1}" for name, src in PLACEHOLDERS)
    print(f"Wrote {os.path.relpath(OUT, ROOT)} ({counts})")


if __name__ == "__main__":
    main()
